### ISSUE TITLE
CDI 4.0 Docs

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/docs#5754]
Currently the only (non-generated) CDI docs are on this page about the differences between JEE 8.0 and 9.1.
https://openliberty.io/docs/latest/jakarta-ee-diff.html

I anticipate that there will be an equivalent page created for the differences between JEE 9.1 and 10.0. This is an issue to cover the CDI 4.0 aspects of that. Note that much of this content will be the same as was in the [beta blog post](https://openliberty.io/blog/2022/08/04/jakarta-core-profile-22009-beta.html) and so the initial content has been copied from there.

-----------------------

## Support for build compatible extensions and observable container state events (CDI 4.0)
CDI allows objects to be bound to lifecycle contexts, to be injected, to be associated with interceptors and decorators, and to interact in a loosely coupled fashion by firing and observing events.
Highlights of CDI 4.0 include support for build compatible extensions and observable container state events. This update also brings in new Jakarta EE 10 versions of the Jakarta Annotations and Jakarta Interceptors APIs.

### Build compatible extensions

Previous versions of CDI allowed users to provide Portable Extensions to customize the CDI application initialization lifecycle. These Build Compatible Extensions make implementing extensions amenable to build-time processing. To implement a Build Compatible Extension, provide an implementation of the `BuildCompatibleExtension` interface, declared via `META-INF/services`. The implementation can provide methods annotated with one of the extension annotations, each of which corresponds to the extension execution phases:

- `@Discovery`
- `@Enhancement`
- `@Registration`
- `@Synthesis`
- `@Validation`

For example, as part of the `Enhancement` phase, this implementation adds an additional `MyQualifier` annotation to the `MyService` type:

```
public class MyExtension implements BuildCompatibleExtension {
    @Enhancement(type=MyService.class)
    public void addMyQualifier(ClassConfig clazz) {
        clazz.addAnnotation(MyQualifier.class)
    }
}
```

### Startup and Shutdown events

Two new observable container state events are now available: Startup and Shutdown. Applications can listen for these events to be notified when the CDI container is starting up and being shut down.

```
@ApplicationScoped
public class MyObserver {
    public void observeStartup(@Observes Startup startupEvent) { {
        System.out.println("CDI Container is starting");
    }

    public void observeShutdown(@Observes Shutdown shutdownEvent) { {
        System.out.println("CDI Container is stopping");
    }
}
```

You can control the order of multiple observer methods by using the `@Priority` annotation.

### Empty beans.xml files

In previous versions of CDI, an empty `beans.xml` file indicated that an archive should be treated as an explicit bean archive (the equivalent of `bean-discovery-mode="all"`). In CDI 4.0, an empty `beans.xml` now causes an archive to be treated as an implicit bean archive (the equivalent of `bean-discovery-mode="annotated"`). If necessary, you can <<cdiConfiguration, set the emptyBeansXmlCDI3Compatibility configuration option>> to enable compatibility with previous versions.

### Unversioned beans.xml files

In previous versions of CDI, a non-empty `beans.xml` file that did not include a `version` attribute defaulted to `bean-discovery-mode="all"`. In CDI 4.0, it defaults to `bean-discovery-mode="annotated"`. However, you should properly version all `beans.xml` files, as shown in the following configuration example:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://jakarta.ee/xml/ns/jakartaee"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/beans_4_0.xsd"
    version="4.0"
    bean-discovery-mode="annotated">
</beans>
```

### Programmatic lookup of beans and instances

A new Handle API is now available to make programmatic inspection of Bean metadata easier. This avoids the need to create instances before they are actually required. You can obtain a `Handle` using the Instance API:

```
public interface Handle<T> extends AutoCloseable {
        T get();
        Bean<T> getBean();
        void destroy();
        void close();
}
```

### Removed APIs

The following previously deprecated CDI APIs have been removed:

* `@New` qualifier - replaced by `@Dependent` beans.
* `Bean#isNullable()` - has not been used by the implementation since CDI 1.1.
* `BeanManager#fireEvent()` - Use `BeanManager.getEvent()` instead.
* `BeanManager#createInjectionTarget(AnnotatedType)` - replaced by `BeanManager#getInjectionTargetFactory(AnnotatedType)`
* `BeforeBeanDiscovery#addAnnotatedType(AnnotatedType)` - replaced by `BeforeBeanDiscovery#addAnnotatedType(AnnotatedType, String)`

### Configuration

The Liberty `<cdi12>` server.xml configuration element has been superseded by a new `<cdi>` element, which applies to CDI versions 1.2 and later. For example:

```
<cdi enableImplicitBeanArchives="false" emptyBeansXmlCDI3Compatibility="true"/>
```

* The `enableImplicitBeanArchives` attribute is the same as it was in previous versions.
  - If set to `true`, which is the default, then archives that do not contain a `beans.xml` file are treated as Implicit Bean Archives and scanned for classes that have bean defining annotations.
  - If set to `false`, then archives that do not contain a `beans.xml` file are not scanned for annotated classes.

* The `emptyBeansXmlCDI3Compatibility` attribute applies only to CDI 4.0.
  - If set to `true`, then an archive that contains an empty `beans.xml` file is treated as an explicit bean archive, as it was in CDI 3.0 and earlier.
  - If set to `false`, which is the default, then an archive that contains an empty `beans.xml` file is treated as an implicit bean archive. This is equivalent to setting `bean-discovery-mode="annotated"`..

To use the CDI 4.0 feature, add `cdi-4.0` to your `server.xml`:

```
<featureManager>
  <feature>cdi-4.0</feature>
</featureManager>
```

**Comment by dmuelle** [comment]
Thanks @tevans78 - we also have these CDI-related topics

[Context and Dependency Injection beans](https://openliberty.io/docs/latest/cdi-beans.html)
[RESTful Web Services integration with CDI](https://openliberty.io/docs/latest/jaxrs-integration-cdi.html)

I can check these against the differences listed in the previous comment but they should also be reviewed by SME as part of this issue.

**Comment by tevans78** [comment]
@dmuelle Strange that the `Context and Dependency Injection beans` page is under a `RESTful services` section? That is why I didn't find it.

**Comment by dmuelle** [comment]
OK-  I can move that out to be a top-level topic w/in the Development section with the next release

**Comment by dmuelle** [comment]
Hi @tevans78 ,

I've added these updates to a new draft topic for differences between EE 10.0 and 9.1

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi

At this time, only the CDI section is ready for review. Let me know if ay changes are needed.

I also updated the information about empty/unversioned `beans.xml` files on the [Context and Dependency Injection beans](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html) page. If you see anything else there or on [RESTful Web Services integration with CDI](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jaxrs-integration-cdi.html) that needs an update, just let me know. Per your previous comment, I moved this page out of the RESTful Services section to be its own top-level entry in the Development section of the TOC.

When you're satisfied with the draft, you can add the `technical reviewed` label to this issue to sign off and the updates will publish with the 23.0.0.2 release ( unless the epic moves out). Thanks

**Comment by tevans78** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi
1. In the opening sentence there is a typo in the feature name; `cid-4.0` should be `cdi-4.0`.
2. I need to double check the code but I think we should change the "Unversioned beans.xml files" section to be "Non-empty beans.xml files" and then remove mention of the `version` attribute.
3. In "Programmatic lookup of beans and instances", the example given is an example of the interface that you could use, not _how_ you could use it. We either need to re-word that section slightly or provide a new example.

**Comment by tevans78** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html
1. In the CDI scopes section, there is an example beans.xml which is slightly wrong (the schema is 1.1 but the version is 4.0). I suggest using the example beans.xml from the differences page above.
2. In the text below that beans.xml example, Ben suggested adding more detail (and complexity) to more fully explain the variations in how CDI Archives can be configured. I'm not sure ... I don't think these are meant to be exhaustive reference docs?
3. The last sentence of that section again mentions a beans.xml file which does not have a `version` attribute. I think we should change that to something like;
```
Also in CDI 4.0 and later, a non-empty beans.xml file which does not specify the `bean-discovery-mode` attribute, defaults this value to "annotated".
```

**Comment by dmuelle** [comment]
Thanks @tevans78 - i've updated the drafts

## [Differences between Jakarta Contexts and Dependency Injection 4.0 and 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi)

1. fixed typo
2. Changed  "Unversioned beans.xml files" ---> "Non-empty beans.xml files" and removed mention of the `version` attribute.
3. what would be more helpful for someone understanding the "Programmatic lookup" changes- seeing the interface or a worked example? For now, changed the the text to:

> You can obtain a Handle instance by using the Instance API, which uses the following syntax.

## [Context and Dependency Injection beans](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html)

1. updated the beans.xml example to match the one from the differences page
2. We can add more detail if needed. The docs aren't meant to be exhaustive or reproduce the spec, but they should cover anything Liberty-specific and should provide enough detail so that someone writing an app can understand how to get the functionality they need in the majority of cases. We could also add create a new issue to improve this doc, if needed. Let me know what you think.
3. edited the suggested sentence but left the following sentences in that paragraph as they were. Not sure if that was the intention- the draft now says

> Also in CDI 4.0 and later, a non-empty `beans.xml` file that does not specify the `bean-discovery-mode` attribute defaults this value to annotated. Therefore, by default, only objects with CDI bean-defining annotations are discovered as CDI beans. However, always properly specify a version for all `beans.xml` files, as shown in the previous example.


If any further changes are needed, just let me know. Otherwise you can sign off by adding the `technical reviewed` label to this issue and the doc will publish with EE 10 Ga. Thanks

**Comment by Emily-Jiang** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi
1. In the section of **Empty beans.xml** files and **Non-empty beans.xml files**, there are repetitive information. I am wondering whether to merge the two sections into one
**The bean-discovery-mode attribute absent in beans.xml**
In the version of CDI prior to CDI 4.0, if a beans.xml file (empty or non-empty) does not set the attribute of **bean-discovery-mode**, it is treated as if setting the bean-discovery-mode="all" attribute in the file. In CDI 4.0, it is treated as if setting the bean-discovery-mode="annotated" attribute in the file.
For an empty beans.xml, you can [set the emptyBeansXmlCDI3Compatibility attribute](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdiConfiguration) to enable compatibility with previous versions. If you set this attribute to true in CDI 4.0, any archives that contain an empty beans.xml file are treated as explicit beans archives.
For an non-empty beans.xml, it is always a best practice to properly specify a version for all beans.xml files, as shown in the following example.
//add the beans.xml snippet here.

**Comment by Emily-Jiang** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html
1. Context and Dependency Injection beans => Contexts and Dependency Injection (CDI)
2. CDI enables Java object dependencies to be automatically injected at run time => CDI enables Java object dependencies to be automatically injected

**Comment by dmuelle** [comment]
Thanks for reviewing @Emily-Jiang. I've updated the draft: 

## [Differences between Jakarta Contexts and Dependency Injection 4.0 and 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdi)

- [x]  updated title to **Context and Dependency Injection (CDI)**

- [x] CDI enables Java object dependencies to be automatically injected at run time => CDI enables Java object dependencies to be automatically injected

## [Context and Dependency Injection beans](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/cdi-beans.html)

- [x]  Consolidated empty/nonempty sections into [The bean-discovery-mode attribute in empty and non-empty beans.xml files](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_the_bean_discovery_mode_attribute_in_empty_and_non_empty_beans_xml_files)


If any further changes are needed, just let me know. Otherwise you can sign off by adding the `technical reviewed` label to this issue and the doc will publish with EE 10 Ga. Thanks

**Comment by tevans78** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_the_bean_discovery_mode_attribute_in_empty_and_non_empty_beans_xml_files

`For an empty beans.xml file in CDI 4.0, you can set the emptyBeansXmlCDI3Compatibility attribute to enable compatibility with previous versions.`

It is not clear that `emptyBeansXmlCDI3Compatibility` is an attribute on the `cdi` element in server.xml (not beans.xml). Would be good to link to the section below - https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdiConfiguration

**Comment by dmuelle** [comment]
Thanks @tevans78 - the draft is updated to clarify that

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_the_bean_discovery_mode_attribute_in_empty_and_non_empty_beans_xml_files

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this is ready for peer reivew

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

CDI provides Portable Extensions to customize the CDI application initialization lifecycle. In CDI 4.0, Build Compatible Extensions make implementing extensions amenable to build-time processing.
->
CDI provides Portable Extensions to customize the CDI application initialization lifecycle. In `CDI 4.0`, Build Compatible Extensions make implementing extensions amenable to build-time processing.
( One more question -> Should Portable Extensions & Build Compatible Extensions be in CAPS ? - I ask because in the very next Para - Build Compatible Extensions is not in CAPS.)

The implementation can provide methods that are annotated with one of the following extension annotations, each of which corresponds to an extension execution phase.
->
The implementation can provide methods that are annotated with one of the following extension annotations**. Each of these annotations corresponds to an execution phase.**

For example, as part of the `Enhancement` phase, the implementation in the following example...
->
For example, as part of the `@Enhancement` annotation, the implementation in the following example...

Two new observable container state events are available in CDI 4.0: `Startup` and `Shutdown`. 
->
Two new observable container state events are available in `CDI 4.0`: `Startup` and `Shutdown`.  

In CDI 4.0, a `beans.xml` file that does not specify the `bean-discovery-mode` attribute is treated as if the attribute is set to `bean-discovery-mode="annotated"`. In CDI 3.0 and earlier, a `beans.xml` file that does not specify the `bean-discovery-mode` attribute is treated as if the attribute is set to `bean-discovery-mode="all"`. These settings apply to both empty and non-empty `beans.xml` files.
->
In `CDI 4.0`, a `beans.xml` file that does not specify the `bean-discovery-mode` attribute is treated as if the attribute is set to `bean-discovery-mode="annotated"`. In `CDI 3.0` and earlier, a `beans.xml` file that does not specify the `bean-discovery-mode` attribute is treated as if the attribute is set to `bean-discovery-mode="all"`. These settings apply to both empty and non-empty `beans.xml` files.

For an empty `beans.xml` file in CDI 4.0, you can set the `emptyBeansXmlCDI3Compatibility` attribute for the [cdi](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cdi.html) element to enable compatibility with previous versions. If you set this attribute to true in your `server.xml` file, any archives that contain an empty `beans.xml` file are treated as explicit beans archives. For more information, see [Server.xml configuration element and attribute updates](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdiConfiguration).
->
For an empty `beans.xml` file in `CDI 4.0`, you can set the `emptyBeansXmlCDI3Compatibility` attribute for the [cdi](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cdi.html) element to enable compatibility with previous versions. If you set this attribute **to `true`** in your `server.xml` file, any archives that contain an empty `beans.xml` file are treated as explicit beans archives. For more information, see **the** [Server.xml configuration element and attribute updates](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#cdiConfiguration).

Also, Acrolinx suggests non hyphenated -> for non-empty

In CDI 4.0, a new Handle API is available to simplify programmatic inspection of bean metadata. This API avoids the need to create instances before they are required. You can obtain a Handle instance by using the Instance API, which uses the following syntax.
->
In `CDI 4.0`, a new Handle API is available to simplify **the** programmatic inspection of bean metadata. This API avoids the need to create instances before they are required. You can obtain a `Handle` instance by using the `Instance` API, which uses the following syntax.

The following previously deprecated CDI APIs are removed in CDI 4.0.
`@New` qualifier, which replaced by `@Dependent` beans.
Bean#isNullable(), not used by the implementation since CDI 1.1.
->
The following previously deprecated CDI APIs are removed in `CDI 4.0.`
`@New` qualifier, which **is** replaced by `@Dependent` beans.
`Bean#isNullable()`, not used by the implementation since `CDI 1.1.`

The `emptyBeansXmlCDI3Compatibility` attribute applies only to CDI 4.0. If this attribute is set to `true`, an archive that contains an empty `beans.xml` file is treated as an explicit bean archive, as it was in CDI 3.0 and earlier. If this attribute set to `false`, which is the default, then an archive that contains an empty `beans.xml` file is treated as an implicit bean archive.
->
The `emptyBeansXmlCDI3Compatibility` attribute applies only to `CDI 4.0`. If this attribute is set to `true`, an archive that contains an empty `beans.xml` file is treated as an explicit bean archive, as it was in `CDI 3.0` and earlier. If this attribute **is** set to `false`, which is the default, then an archive that contains an empty `beans.xml` file is treated as an implicit bean archive.

**Comment by tevans78** [comment]
@ramkumar-k-9286 @dmuelle 
"CDI 4.0" is not code and so does not need to be in a code block. It is just an abbreviated way of saying the name of the specification. For comparison, `cdi-4.0` is code because it is talking about the short Liberty feature name that you would use in server.xml.

For similar reasons, I would actually be inclined to remove the code block from "the Enhancement phase". If we were talking directly about the code annotation that you use then it would be "the `@Enhancement` annotation".

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 , I've made changes per your review, with the exception of putting CDI 4.0 in a code block, as Tom pointed out.

Also:

> Also, Acrolinx suggests non hyphenated -> for non-empty

Although acrolinx generically recommends not to use hyphens with "non",  in this case IBM Terminology says to use "non-empty", probably because it is more readable than "nonempty"
